name: test
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - '*'
env:
  GOPROXY: https://proxy.golang.org
  CGO_ENABLED: 0
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'

      - name: Lint
        run: |
          make lint

      - name: Test
        run: |
          make test